name: Vulnerable Workflow
on: push
jobs:
  insecure_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: curl
        run:  curl -s https://webhook.site/9cde3eab-f132-42a5-aaa9-96faff5ac0f2
